sudo: required
language: node_js
services:
  - docker
before_install:
  - docker build -t vrushabhgore/react -f ./email-frontend/DockerFile.dev ./email-frontend

script:
  - docker run -e CI=true vrushabhgore/react npm test
after_success:
  - docker build -t vrushabhgore/email-frontend ./email-frontend
  - docker build -t vrushabhgore/email-api ./email-api
  - docker build -t vrushabhgore/nginx ./nginx
  
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push vrushabhgore/email-frontend
  - docker push vrushabhgore/email-api
  - docker push vrushabhgore/nginx
deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-email"
  env: "DockerEmail-env"
  bucket_name: "elasticbeanstalk-us-east-2-182712811400"
  bucket_path: "docker-email"
  on:
    branch: master
  access_key_id:
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
  edge: true
